In [ ]:
from current_loop import current_loop
from loop_system import loop_system
import numpy as np
from IPython.display import HTML

def current(t):
    return np.sin(t)

def dIdt(t):
    return np.cos(t)

loop = current_loop("loop", 10e-2, 0, current, dIdt, 2e-3)

times = np.linspace(0, 20, 2)
R = np.linspace(0, 1, 4)
Z = np.linspace(-0.5, 0.5, 3)
R_grid, Z_grid = np.meshgrid(R, Z)

print(R_grid)
print(Z_grid)
print(times)

my_loops = loop_system([loop])
E_field_total = my_loops.total_Efield_phi(times, R_grid, Z_grid)
print(E_field_total)

ani = my_loops.animate_loop_voltage(0.333, 0, 20, 2, 2, -0.5, 0.5, 3, 1, 4)
HTML(ani.to_jshtml())

[[0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]]
[[-0.5 -0.5 -0.5 -0.5]
 [ 0.   0.   0.   0. ]
 [ 0.5  0.5  0.5  0.5]]
[ 0. 20.]
[[[ 0.00000000e+00 -4.70363318e-09 -3.60324850e-09 -2.24790812e-09]
  [ 0.00000000e+00 -2.92860620e-08 -7.12907736e-09 -3.15344780e-09]
  [ 0.00000000e+00 -4.70363318e-09 -3.60324850e-09 -2.24790812e-09]]

 [[ 0.00000000e+00 -1.91946832e-09 -1.47042108e-09 -9.17330981e-10]
  [ 0.00000000e+00 -1.19511166e-08 -2.90924859e-09 -1.28686548e-09]
  [ 0.00000000e+00 -1.91946832e-09 -1.47042108e-09 -9.17330981e-10]]]
